### ISSUE TITLE
<> operator in DatabaseL2->applyEvents()

### ISSUE THREAD

**Issue by danielbachhuber** [lcache/lcache#23]
`DatabaseL2->applyEvents()` has this `<>` operator for excluding the cache pool:

```
$applied = 0;
try {
    $sth = $this->dbh->prepare('SELECT "event_id", "pool", "address", "value", "created", "expiration" FROM ' . $this->prefixTable('lcache_events') . ' WHERE "event_id" > :last_applied_event_id AND "pool" <> :exclude_pool ORDER BY event_id');
    $sth->bindValue(':last_applied_event_id', $last_applied_event_id, \PDO::PARAM_INT);
    $sth->bindValue(':exclude_pool', $l1->getPool(), \PDO::PARAM_STR);
    $sth->execute();
} catch (\PDOException $e) {
    $this->logSchemaIssueOrRethrow('Failed to fetch events', $e);
    return null;
}
```

Why is the cache pool excluded? https://github.com/lcache/wp-lcache/pull/42 fails when the pool is excluded, and passes when it's not. Ignore the fact that it's currently passing right now — something else broke in the test suite.

**Comment by davidstrauss** [comment]
This is not a bug, at least in that part of the code. There's simply no reason an L1 should synchronize events that it created; it already knows those events happened and has incorporated them into its local cache. I will look at the test that's failing in the WordPress implementation.

**Comment by davidstrauss** [comment]
It appears that your test case breaks through the abstractions that, in normal use, automatically apply writes to the local L1 pool so that the corresponding events (ones originating from the local pool) can be ignored later.

Testing LCache synchronization from a WordPress-side test is impractical given how the library intentionally abstracts everything beyond the need to call `->synchronize()` before using the cache the first time during a request. The unit tests in the LCache library itself handle synchronization tests by creating multiple "integrated" caches with independent L1s and a shared L2. Those tests already verify the visibility of a local write without synchronization and the visibility of a write on a separate pool following synchronization.

I would encourage additions to LCache's own unit test suite if you have concerns about the correctness of synchronization.

**Comment by danielbachhuber** [comment]
> It appears that your test case breaks through the abstractions that, in normal use, automatically apply writes to the local L1 pool so that the corresponding events (ones originating from the local pool) can be ignored later.

Aka, user error :) My bad.

> I would encourage additions to LCache's own unit test suite if you have concerns about the correctness of synchronization.

In this case, I just want to have a smoke test that it's working. 

Thanks!
