### ISSUE TITLE
Redundant set in excess overhead case - Integrated::set()

### ISSUE THREAD

**Issue by DeanMarkTaylor** [lcache/lcache#47]
Following up on my comment regarding code / line:
https://github.com/lcache/lcache/blob/master/src/Integrated.php#L44

```
                $event_id = $this->l2->delete($this->l1->getPool(), $address);
                if (!is_null($event_id)) {
                    $this->l1->set($event_id, $address, $value, $expiration);
                }
```

https://github.com/lcache/lcache/commit/d38ada26ee8e5522b7b7840d47476a3c3d5d58f3#commitcomment-19344043

> It's possible for `$this->l1->set` and then `$this->l1->setWithExpiration` to be called immediately after, is this expected here?

https://github.com/lcache/lcache/commit/d38ada26ee8e5522b7b7840d47476a3c3d5d58f3#commitcomment-19345176

> You're right. It looks like it's likely a redundant set in the excess overhead case. Would you mind filing an issue so we can (1) add a corresponding unit test and (2) fix the code? It looks like there's risk of setting to the L1 with a null event ID from the L2 deletion if the L2 deletion fails.

**Comment by davidstrauss** [comment]
I ran into issues related to this bug while implementing SQLiteL1 because I made it strict about each write to a key being newer than (and not just the same age as) previous ones in terms of event IDs. The SQLiteL1 wouldn't pass the threshold test because the issue (which you found) involved two writes to L1 with the same event ID. This is now fixed, and I've tightened up the other L1 implementations to fail under similar circumstances.

Thanks again for your eagle eye!
