### ISSUE TITLE
Introduce getMulti()

### ISSUE THREAD

**Issue by danielbachhuber** [lcache/lcache#55]
When fetching a known set of keys, it would be nice if LCache supported fetching them in batch.

**Comment by davidstrauss** [comment]
This wouldn't provide a major performance benefit, but there's a potential other reason below.

For L1, APCu doesn't offer any batch fetching API for arbitrary keys, so LCache would have to do the same sort of looping you're trying to avoid. It might make sense if we implemented a SQLite L1, but still not an enormous amount because the cost of looping when you're calling a local data store is usually pretty negligible.

For L2, there are a couple reasons why this wouldn't improve things much:
- The DatabaseL2 schema doesn't support an efficient multi-get with a simple `SELECT`. It might be possible to put the looping in a stored procedure, risking pulling down some stale items (that would be pruned PHP-side), or [joining against the same table](http://stackoverflow.com/a/1313293) to find the latest entry for each item, but all of those substantially complicate the design.
- Optimizing the L2 around reads isn't very important because every missed read gets cached in L1 as it's read, and every new write replicates down to L1 before there's even a chance to read it on subsequent requests.

However, if it makes the lives of people consuming the API easier, I'd be happy to move the loop to the LCache library. Obviously, many CMS cache APIs expect such an operation, and it's a bit silly to reimplement the loop in each adapter. Is code de-duplication a primary goal for this issue?

**Comment by danielbachhuber** [comment]
> Is code de-duplication a primary goal for this issue?

Nope. The assumption was that a multi-get would be more performant because it would be reducing the cost of requests over the network.

**Comment by davidstrauss** [comment]
Okay, well then I will close this for now. I think we should re-open it or create a new issue if we find at least one major efficiency opportunity that requires it and affects production (rather than testing) implementations.
