### ISSUE TITLE
Question on how this works

### ISSUE THREAD

**Issue by joehoyle** [lcache/lcache#86]
I feel like I'm missing a very important piece of the puzzle on how this implementation works. 

if I have web server A and web server B:

1. Web server A gets cache item `foo` from L2, puts it into L1.
1. Web server B updates cache item `foo`, pushes it to L2 (and it's "local L1").
1. Web server A again get cache item `foo` from L1, however this is now stale.

How is Web server A meant to know to invalidate it's L1 stale cache of `foo` with checking the L2 cache for a newer cache value? There's only 2 solutions I see to this:

1. Web server A just keeps a stale `foo` in the L1 cache, and can fall into a split-brain scenario.
1. Web server A just always has to check L2 cache for invalidations on it's L1 cache, rendering the whole point of having a local cache pointless.

I've been looking through the code, but I can't seem to find where this is handled.

Thanks!

**Comment by joehoyle** [comment]
Aha, finally found the answer I think, every time a PHP process starts you are meant to do a `synchronize` with the L2: https://github.com/lcache/lcache/blob/b4b221235977e0b5ec4f58cb02ffd2122a2f1023/src/Integrated.php#L119

This is option 2 of what I thought might be happening, for anyone else curious.

**Comment by danielbachhuber** [comment]
Yep. The system is event-based, and the wake-up mechanism ensures L1 is synchronized each page load.

If you're considering this for production, beware of https://github.com/lcache/wp-lcache/issues/138. You'd probably want to implement some alternative L1 cache.

**Comment by jchristi** [comment]
@danielbachhuber so that means that if a cache item changes in L2 _after_ a local php process has started and synced with L2, then the process will still have a stale value? A less frequently occurring issue for sure, but still one to be aware of right?

**Comment by danielbachhuber** [comment]
> so that means that if a cache item changes in L2 _after_ a local php process has started and synced with L2, then the process will still have a stale value?

Correct.

> A less frequently occurring issue for sure, but still one to be aware of right?

Sure, although I haven't heard of any real-world manifestations of this scenario before (at least as it relates to WordPress).

The most common thorny object cache problem for WordPress is https://github.com/pantheon-systems/wp-redis/issues/221

**Comment by davidstrauss** [comment]
> Web server A just always has to check L2 cache for invalidations on it's L1 cache, rendering the whole point of having a local cache pointless.

I'm just noticing this issue now, but I'd like to explain that the L1 is quite far from "pointless." The L1 cache achieves at least a couple goals that standard caching models (just memcached or Redis over the network) cannot:

- As @danielbachhuber mentioned, the synchronization only happens once per page load. The only further communication with L2 during a page load is (1) on writes to the cache and (2) on L1 misses, which only occurs for items that have never been read or written for the local L1.
- The synchonization model means that large items do not typically traverse the network on reads. This means that network traffic scales according to cache writes rather than cache reads. Given that most network links are symmetric and most caches have hit rates of 95%+, LCache yields a 10X or better improvement in scalability before saturating network links.

Even if LCache checked for coherency on every read (which it does not), the second goal would still be served (e.g. just as it is in HTTP with ETags and code 304 responses). Not having to send large data over the network is still a benefit even if the number of requests remains the same.

> so that means that if a cache item changes in L2 after a local php process has started and synced with L2, then the process will still have a stale value?

As above, @danielbachhuber is correct, but I'd like to add that _any_ system relying on read-after-write cache coherency between different PHP pools is brittle (in terms of race conditions) without adding new, blocking synchronization mechanisms (which is almost always a bad practice in PHP and WordPress).

Even if the cache were coherent between the two PHP pools, you'd still have to ensure that one node completed the write before the other node reads it.* Otherwise, you're still rolling dice about whether the other node has written its changes by the time you're trying to read them. LCache just acknowledges that relying on cache updates performed by someone else (e.g. another PHP pool) in the middle of a request is both uncommon and unsafe. So, LCache relaxes the coherency further along that same path to gain performance and scalability. In other words, we sacrifice correctness that mostly matters theoretically for results that we know matter in practice.

For long-running processes (e.g. cron or CLI tools), LCache can run with a null L1 that ensures every read always gets the freshest data, even if that data is changing while the client is running. Most consumers of LCache choose to do this when a CLI-based environment is detected.

*This would be possible by blocking or polling, but neither is desirable in the middle of a PHP request.

**Comment by jchristi** [comment]
@davidstrauss what are the implications of this say during a cache clear on a drupal site under heavy traffic? I guess it would help for reads but not for writes (which can cause a memcache stampede if protection isn't enabled). The initial read/sync could take longer if stampede protection is enabled, but it would at least occur only once at the beginning and every subsequent read is local. Writes would be the same as without LCache.

**Comment by davidstrauss** [comment]
> what are the implications of this say during a cache clear on a drupal site under heavy traffic?

I think you're mostly correct. LCache functions as a [write-through cache](https://en.wikipedia.org/wiki/Cache_(computing)#Writing_policies), so writes would work as you already understand.

In the L1 layer, I don't expect any stampede effect, as writing to L1 only happens after successfully writing to L2. (I chose this order because L1 can recover from missing writes from L2, but L2 cannot recover from L1 data.) So, stampedes mostly need to be managed in L2.

In L2, we have a hard choice between reducing stampede effects versus maximizing average throughput.

It would be possible, for example, to use transactions to avoid stampedes. However, it would add the overhead of locking the row to-be-written (via SELECT ... FOR UPDATE, reads don't block on this sort of lock in modern DBs), generating the content for the cache entry, writing it, and then releasing the lock. You'd want a check to see, after having acquired the lock, if the cache item is already fresh. This would cause all nodes to wait on one to write the item and then for all nodes to use that item.

This all sounds great, but there are two caveats:

- This sort of locking and use of [MVCC](https://en.wikipedia.org/wiki/Multiversion_concurrency_control) creates substantial overhead for working with the cache values.
- WordPress and Drupal don't let you know at cache miss time that they intend to create the missed object and write it to the cache. We can generally assume they will, but it would be bad when we're wrong, as we'd lock writes to that cache item until the end of the current request.
